name: 'Helix Check'
description: 'Check if solution is following Helix rules'
inputs:
  solution-file:
    description: 'Solution file'
    required: true
    default: 'SitecoreHelix.sln'
  project-name:
    description: 'Project name - prefix for all project files'
    required: true
    default: 'Helixbase'
  website-folder:
    description: 'The name of the folder that always contain website project file'
    required: false
    default: 'website'
  excluded-projects:
    description: 'List of project names that won`t be analyzed. Due to the limitations of GitHub actions it has to be a string with comma delimited project names, e.g. NS.Project1,NS.Project2'
    required: false
    default: ''
outputs:
  result:
    description: 'If helix check successfull'
  time:
    description: 'The time check has been made'
branding:
  icon: 'check-circle'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
