name: 'Helix Check'
description: 'Check if solution is following Helix rules'
inputs:
  solution-file:  # id of input
    description: 'Solution file'
    required: true
    default: 'SitecoreHelix.sln'
  project-name:  # id of input
    description: 'Project name - prefix for all project files'
    required: true
    default: 'Helixbase'
  website-folder:
    description: 'The name of the folder that always contain website project file'
    required: false
    default: 'website'
outputs:
  result: # id of output
    description: 'If helix check successfull'
  time: # id of output
    description: 'The time check has been made'
branding:
  icon: 'check-circle'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
