name: Helix Check - Invalid

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  check_job:
    name: Helix check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Helix Check
        uses: ./ # Uses an action in the root directory
        id: check
        with:
          solution-file: 'example-solution/invalid/Helixbase-Invalid.sln'
          project-name: 'Helixbase'
          website-folder: 'code'
          excluded-projects: 'Helixbase.Foundation.Core,Helixbase.Feature.VersionTrim'
      
      - name: Get the check result
        run: echo "Check result - ${{ steps.check.outputs.result }}"
      
      - name: Get the output time
        run: echo "The time was - ${{ steps.check.outputs.time }}"
